# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Butget' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
# pod 'RealmSwift'
pod 'RealmSwift', '~> 4.4.1'
pod 'SwiftDate', '~> 5.0'
  # Pods for Butget

end
