//
//  CategoriesWorker.swift
//  clean swift
//
//  Created by Felix F on 4/25/20.
//  Copyright (c) 2020 Pedro Ledezma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CategoriesWorker
{
    var storeWorker = CategoryWorker(store: CategoryStoreProtocol)
    func insertInitialCategories(storeWorker:CategoryWorker,completionHandler: () -> Void){
        let economyCategory = Category(name: "Economia", imageName: "economy", news: [News]())
        let tecnologyCategory = Category(name: "Tecnologia", imageName: "tecnologia", news: [News]())
        let incidentCategory = Category(name: "Accedentes", imageName: "incident", news: [News]())
        let sportCategory = Category(name: "Deportes", imageName: "sport", news: [News]())
        
        let categories = [economyCategory,tecnologyCategory,incidentCategory,sportCategory]
        insertCategory(storeWorker:storeWorker,categories:categories,completionHandler:completionHandler)
    }
    func insertCategory(storeWorker:CategoryWorker,categories: [Category],completionHandler: () -> Void){
        guard let category = categories.first else{
            completionHandler()
            return
        }
        var categoriesMutable = categories
        storeWorker.insert(category: category){
            
        }
    }
  
  
}
