//
//  CategoriesModels.swift
//  clean swift
//
//  Created by Felix F on 4/25/20.
//  Copyright (c) 2020 Pedro Ledezma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Categories
{
  // MARK: Use cases
  
  enum DataSource
  {
    struct Request
    {
    }
    struct Response
    {
        var categories:[Category]
    }
    struct ViewModel
    {
        struct DisplayedCategory {
            var title:String
            var image:UIImage?
        }
        var displayedCategory:[DisplayedCategory]
    }
  }
}
