//
//  CategoryWorker.swift
//  clean swift
//
//  Created by Felix F on 4/25/20.
//  Copyright (c) 2020 Pedro Ledezma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
protocol CategoryStoreProtocol {
    func insert(category:Category,completinHandler:() -> Void)
    func fetchAll(completionHandler:(_ Categories:[Category]) -> Void)
}
class CategoryWorker
{
    var store:CategoryStoreProtocol
    init(store:CategoryStoreProtocol){
        self.store = store
    }
    func insert(category:Category,completinHandler:() -> Void){
        store.insert(category: category, completinHandler: completinHandler)
    }
    func fetchAll(completionHandler:(_ Categories:[Category]) -> Void){
        store.fetchAll(completionHandler: completionHandler)
    }
}
