//
//  NewsScenePresenter.swift
//  clean swift
//
//  Created by Felix F on 5/2/20.
//  Copyright (c) 2020 Pedro Ledezma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsScenePresentationLogic
{
  func requestDataSource(response:NewsScene.DataSource.Response)
}

class NewsScenePresenter: NewsScenePresentationLogic
{
  weak var viewController: NewsSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: NewsScene.Something.Response)
  {
    let viewModel = NewsScene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
