//
//  NewsSceneInteractor.swift
//  clean swift
//
//  Created by Felix F on 5/2/20.
//  Copyright (c) 2020 Pedro Ledezma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsSceneBusinessLogic
{
    func requestDataSource(request:NewsScene)
}

protocol NewsSceneDataStore
{
  var categoryIdentifier: Category? { get set }
}

class NewsSceneInteractor: NewsSceneBusinessLogic, NewsSceneDataStore
{
  var presenter: NewsScenePresentationLogic?
  var worker: CategoryWorker(store:CategoryRealmStore())
  var categoryIdentifier: Category?
    
    func requestDataSource(request: NewsScene.DataSource.Request) {
         
    }
    
   
}
