# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weatherApi' do
  pod 'Alamofire','~> 5.1'
pod 'Kingfisher', '~> 5.0'
pod 'NVActivityIndicatorView'
pod 'R.swift'

end
